<?php

namespace PW\MyBundle\Repository;

/**
 * HommeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HommeRepository extends \Doctrine\ORM\EntityRepository
{
}
