<?php

namespace PW\MyBundle\Repository;

/**
 * NotifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotifRepository extends \Doctrine\ORM\EntityRepository
{
}
